### ISSUE TITLE
phpcbf command appends extra dash

### ISSUE THREAD

**Issue by montchr** [valeryan/vscode-phpcbf#10]
When I try to format a file with the formatter provided by this extension, the args provided to `phpcbf` include an extra dash at the end, which causes the command to fail. As seen in the debug output:

```
PHPCBF args:  -q --standard=/path/to/phpcs.xml --stdin-path=/path/to/some/file.php -
```

- If I run `phpcbf` in my terminal with the exact arguments provided by the debug output, the process hangs.
- If I keep the dash and remove the `stdin-path` argument, it hangs.
- If I remove the trailing `-`, it works.
- If I keep only the `standard` arg and remove `-` and `stdin-path`, it works.
- `phpcs` also hangs when I run `phpcs -`, but works when I run `phpcs`

**Comment by valeryan** [comment]
This extension uses standard input (stdin) to process files. You cannot simply run this command from the command line and have it work. The file content is loaded into memory and then printed to the process using stdin. The `-` tells phpcbf to wait for input. `--stdin-path=` is only used as a reference to give the phpcbf process knowledge of where the file content is coming from so that it can do things like apply filters and determine if the file should be ignored, etc... So this command is exactly as it should be. You can check out the docs here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage

What is more likely is that you are feeding the phpcbf process a file that takes too long to process and VS Code kills the worker. This is a setting that you can adjust. If this extension is run in debug mode it will suggest that you change `editor.formatOnSaveTimeout` from the default of 750 milliseconds to something like 2000. However, I have seen it take as long as 5 seconds to process a really dirty file. You can just adjust it upwards until it can handle the file. Be warned you may have to restart each time you change this setting because it seems to break the config reload code.

**Comment by valeryan** [comment]
I have not heard back from you so I can only assume you found a solution. Reopen I guess if you feel you still need additional support.
